### ISSUE TITLE
Incorrect prefix set after grub-install

### ISSUE THREAD

**Issue by ericzinnikas** [openzfs/openzfs-docs#118]
Following the `Ubuntu 20.04 Root on ZFS` guide, I've gotten my system into a state (after doing the `/boot/grub Not Mounted` workaround) where `prefix` in my grub.cfg is not properly set, i.e. it is not `set prefix=($root)'/BOOT/ubuntu_UUID/grub@'`. I'm running mirrored boot drives.

```
# grep prefix=     /boot/efi/EFI/ubuntu/grub.cfg     /boot/efi2/EFI/ubuntu-2/grub.cfg
/boot/efi/EFI/ubuntu/grub.cfg:set prefix=($root)'/grub@'
/boot/efi2/EFI/ubuntu-2/grub.cfg:set prefix=($root)'/grub@'
```

At one point, it definitely was set correctly but now is not (I remember running the command and seeing the UUID). I've reinstalled grub/update-grub/grub-install/etc. Upon reboot I'm greeted with a blank grub prompt, I can use `configfile` to manually load & boot.

The menuentry section in `/boot/grub/grub.cfg` seems correct:
```
menuentry 'Ubuntu 20.04.2 LTS' --class ubuntu --class gnu-linux --class gnu --class os ${menuentry_id_option} 'gnulinux-rpool/ROOT/ubuntu_ABC-5.4.0-65-generic' {
        recordfail
        load_video
        gfxmode ${linux_gfx_mode}
        insmod gzio
        if [ "${grub_platform}" = xen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod zfs
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root  1234
        else
          search --no-floppy --fs-uuid --set=root 1234
        fi
        linux   /BOOT/ubuntu_ABC@/vmlinuz-5.4.0-65-generic root=ZFS=rpool/ROOT/ubuntu_ABC ro  init_on_alloc=0
        initrd  /BOOT/ubuntu_ABC@/initrd.img-5.4.0-65-generic
}
```

From `grub-install --verbose ...`:
```
grub-install: info: grub-mkimage --directory '/usr/lib/grub/x86_64-efi' --prefix '/grub@' --output '/boot/grub/x86_64-efi/core.efi'  --dtb '' --format 'x86_64-efi' --compression 'auto'  --config '/boot/grub/x86_64-efi/load.cfg' 'zfs' 'part_gpt' 'part_gpt' 'search_fs_uuid'
```

**Comment by ddnexus** [comment]
Hi @ericzinnikas ,
I have mirror too, and I see the same `set prefix=($root)'/grub@'` in both boot partitions. The boot works, although I am not sure everything is still OK, since the `grub-probe /boot` fails here. Does it work there?

Besides, should the 2 `grub.cfg` be different or the same? Here they are exactly the same, and that doesn't seem to be right.

I didn't change anything, nor update grub since ages, so whatever happened has to be related to some update.

**Comment by ddnexus** [comment]
@ericzinnikas  I researched it better and re-read my own https://github.com/openzfs/openzfs-docs/issues/55 and related bug/fix: https://github.com/ubuntu/zsys/issues/163 so here are the things that I understood, hoping it might be useful to you:

- The `grub-probe /boot` command fails because it requires root, so `sudo grub-probe /boot` works (I forgot it AGAIN)
- The `set prefix=($root)'/grub@'` should be correct IF you have GRUB in `bpool/grub` e.g.
    ```
    zfs list -r bpool | grep grub
    bpool/grub                5.38M  1.05G     5.38M  /boot/grub
    ```
- The `set prefix=($root)'/BOOT/ubuntu_UUID/grub@'` is the outdated and not working workaround (grub mounted at `bpool/BOOT/ubuntu_UUID/grub`), so it should not be in your setup unless you are on the old broken way to use it (and in that case you should fix it with GRUB in `bpool/grub`)
- The 2 `grub.cfg` are identical because they are both pointing to the same ZFS boot partition which is mirrored, so it has the same id. Notice the fs_uuid in the file is the HEX version of the UUID that appears in GUI apps like Disks. The fstab mounts both efi dirs from the 2 efi partitions, so you should be able to boot even if one disk fails, because the boot is still pointing to the same mirrored bpool.

HTH

**Comment by rlaager** [comment]
Hopefully this was resolved one way or another by now. If you're still having trouble: if it were me, I'd make sure bpool was imported, all the filesystems were mounted as expected, then I'd redo the GRUB config and install with update-grub and grub-install. That said, it sounds like you've done that, so I really don't know what else to say.
