### ISSUE TITLE
zsys install fails (ubuntu 20.04 luks)

### ISSUE THREAD

**Issue by l-t-k** [openzfs/openzfs-docs#120]
I'm using the 20.04 guide (with single boot drive, luks and swap) and everything goes fine until step 4.9 and after installing zsys:

_After this operation, 13.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 zsys amd64 0.4.8 [3636 kB]
Fetched 3636 kB in 1s (5019 kB/s)
Selecting previously unselected package zsys.
(Reading database ... 24292 files and directories currently installed.)
Preparing to unpack .../archives/zsys_0.4.8_amd64.deb ...
Unpacking zsys (0.4.8) ...
Setting up zsys (0.4.8) ...
**modprobe: FATAL: Module zfs not found in directory /lib/modules/5.8.0-41-generic**
Created symlink /etc/systemd/user/timers.target.wants/zsys-user-savestate.timer → /usr/lib/systemd/user/zsys-
user-savestate.timer.
Created symlink /etc/systemd/system/default.target.wants/zsys-commit.service → /lib/systemd/system/zsys-commi
t.service.
Created symlink /etc/systemd/system/timers.target.wants/zsys-gc.timer → /lib/systemd/system/zsys-gc.timer.
Created symlink /etc/systemd/system/sockets.target.wants/zsysd.socket → /lib/systemd/system/zsysd.socket.
root@ubuntu:/# zsysctl version
zsysctl	0.4.8
**ERROR couldn't connect to zsys daemon: connection error: desc = "transport: Error while dialing dial unix /run/zsysd.sock: connect: no such file or directory"**_

**Comment by jonaslm** [comment]
Same issue here, but using mirrored bootpool and zfs native encryption... it seems like it's some sort of chroot issue?

As above, zsys complains that `Module zfs not found in directory /lib/modules/5.8.0-41-generic`

If I `ls /lib/modules` inside the chroot, I have this:
```
root@ubuntu:/# ls /lib/modules/
5.4.0-65-generic
```

If I do the same outside the chroot, I have this:
```
root@ubuntu:~# ls /lib/modules/
5.8.0-41-generic
```

I tried proceeding with the guide despite the zsys errors, but had later issues pop up after rebooting (/boot not getting mounted and `dpkg-reconfigure grub-efi-amd64` not allowing me to pick the mirrored ESP partition).

**Comment by jonaslm** [comment]
Reading the guide more carefully, I realize it specifically says to use the **20.04.1** version of the live CD, while I had downloaded the latest one (20.04.2). I will make another attempt with the older liveCD later.

**Comment by rlaager** [comment]
I do need to update for 20.04.2 at some point, but I don't know when that will be nor do I have an idea if that is related to this issue (which I haven't looked at, but this is in my inbox).

**Comment by jonaslm** [comment]
Tried with the older 20.04.1 liveCD, but I got the same issues (it still looks like it's trying to get the parent modules folder, while the /lib/modules that exists in the chroot environment differs slightly).
```
Setting up zsys (0.4.8) ...
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.4.0-42-generic
```

Got the same issue after reboot too, while it boots like it should, `dpkg-reconfigure grub-efi-amd64` doesn't prompt me to "Select (using the space bar) all of the ESP partitions (partition 1 on each of the pool disks)" and neither /boot/efi nor bpool is mounted at all (should they be?). Not sure if that issue is even related to the earlier zfs module errors.

I'm a bit of out of my element, so I'm not entirely sure how to proceed from here.

**Comment by jonaslm** [comment]
I "fixed" the grub issue by just doing `dd if=/dev/nvme0n1p1 of=/dev/nvme1n1p1` which seems to let me boot from both drives anyway (though I suppose won't be kept up to date properly). Haven't noticed any other strange fallout from the zfs module issues during installation... yet

**Comment by rlaager** [comment]
The module errors are a red herring and can be ignored. That's due to a mismatch between the Live CD and the chroot. The module is loaded, so that's not a problem. The zed errors are not a problem, since zed is started manually later.

I was able to reproduce the bpool not being imported. I suspect that's because it's not ending up in the cache inside the chroot.

Try this:
```
# Move /boot/grub out of the way, or it will prevent mounting /boot:
mv /boot/grub /grub-old

zpool import bpool
mount /boot/efi

# Rebuild /boot/grub (alternatively, copy back the copy from above):
update-grub
```
