### ISSUE TITLE
Question about use of legacy mountpoint and zfs-mount-generator

### ISSUE THREAD

**Issue by rHermes** [openzfs/openzfs-docs#123]
@ne9z, I have the following issue with the Arch Linux Root on ZFS HOWTO:

I'm not sure I understand the reason the `bpool_$INST_UUID/BOOT/default` dataset is created with a legacy mountpoint in the arch guide, but not as legacy in the debian guide? What is the motivation behind the legacy mountpoint in the arch guide?

Another question is  https://wiki.archlinux.org/index.php/ZFS#Automatic_Start mentions that you can use either `zfs-mount` or `zfs-mount-generator` to mount filesystems at boot. But in the official https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.html#system-configuration installation, both are used. Why are both used?

**Comment by ne9z** [comment]
## canmount=legacy
A typical BE looks like the following:
```
NAME                              MOUNTED  MOUNTPOINT          CANMOUNT
bpool_13sijd/BOOT/default         yes      legacy              noauto
bpool_13sijd/BOOT/BE1             no       legacy              noauto
rpool_13sijd/ROOT/default         yes      /                   noauto
rpool_13sijd/ROOT/BE1             no       /                   noauto
```
After entering BE1:
```
NAME                              MOUNTED  MOUNTPOINT          CANMOUNT
bpool_13sijd/BOOT/default         no       legacy              noauto
bpool_13sijd/BOOT/BE1             yes      legacy              noauto
rpool_13sijd/ROOT/default         no       /                   noauto
rpool_13sijd/ROOT/BE1             yes      /                   noauto
```
Firstly, these datasets must be `canmount=noauto` to ensure only the correct dataset is mounted. Datasets will mount upon each other if `canmount=on`, resulting in
```
NAME                              MOUNTED  MOUNTPOINT          CANMOUNT
rpool_13sijd/ROOT/default         yes      /                   on
rpool_13sijd/ROOT/BE1             yes      /                   on
```
Secondly, `zfs-mount-generator` does not mount `canmount=noauto` datasets. The root dataset is specified with `root=ZFS=rpool_13sijd/ROOT/default` and will be mounted by initrd regardless of `canmount=noauto`, but this is not the case for `bpool_13sijd/BOOT/default`.

To mount `bpool_13sijd/BOOT/default` at boot while using `canmount=noauto`, `mountpoint=legacy` must be used. The boot environment manager will edit the `/etc/fstab` entry when creating BEs.

Debian guide is not written to support BEs therefore this issue is not addressed.
## zfs-mount or zfs-mount-generator
Arch Wiki is wrong, `zfs-mount` can not be used for system datasets.

Namely, systemd will get ahead of `zfs-mount` and populate `/var/*/*` with files, rendering the mountpoints non-empty. `/var/log` dataset will then refuse to mount on a non-empty mountpoint.
`zfs-mount-generator` is created to address this problem.

 When booting the computer, `zfs-mount-generator` is executed first to mount datasets on `bpool` and `rpool`.

`zfs-mount`, on the other hand, finds and mounts datasets on other pools. Say you have another data pool named `mypool`, `zfs-mount` will mount its datasets for you.

If such additional pools do not exist, `zfs-mount` service can be safely disabled.

**Comment by rHermes** [comment]
Thanks for the quick answer and the awesome guide in general!

I think I understand the difference now between the `zfs-mount`, but I just wanted to note that I tried an install now where I just used zfs-mount and it boots just fine. Could it just be me getting lucky with the timing of the logs, or has something changed?

**Comment by ne9z** [comment]
@rHermes: Just performed a clean installation w/o `zfs-mount-generator`. Indeed, the `/var/*` datasets are properly mounted.

However, I still recommend you to use `zfs-mount-generator` to deterministically mount datasets, as described in the guide.

For more discussion on this topic, see [this issue](https://github.com/openzfs/zfs/issues/4898).

**Comment by rHermes** [comment]
Ah, this makes a lot of sense then!

Thanks for going through the install procedure and checking :) I'll switch to using `zfs-mount-generator` as you advise :)
