### ISSUE TITLE
Compression for performance

### ISSUE THREAD

**Issue by grahamperrin** [openzfs/openzfs-docs#232]
https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Workload%20Tuning.html#lz4-compression

LZ4 is recommended, should this now be Zstandard?

https://github.com/openzfs/openzfs-docs/blob/2255c092be9d9eb6b72e081ca86baf52849f1d3c/docs/Performance%20and%20Tuning/Workload%20Tuning.rst?plain=1#L388-L402

https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#Native_Properties

From <https://freebsdfoundation.org/wp-content/uploads/2021/05/Zstandard-Compression.pdf> thanks @allanjude: 

> …  One of the main advantages of Zstd is that the decompression speed is independent of the compression level. For data that is written once but read many times, Zstd allows the use of the highest compression levels without a performance penalty. …

**Comment by gmelikov** [comment]
For a common "don't hurt by default" lz4 still has several advantages overall:
- It's still noticeably faster https://github.com/facebook/zstd
- It's supported by Grub, so zstd by default will break some use cases (because it enables new feature flag)

So, zstd is really great, but a "common" recommendation it's still lz4 for me.

**Comment by gmelikov** [comment]
We can change docs anytime on default compression type change, I'll close this issue for now.
