### ISSUE TITLE
NixOS Root on ZFS + UEFI: grub-install /boot doesn't look like an EFI partition.

### ISSUE THREAD

**Issue by jacobgreenleaf** [openzfs/openzfs-docs#294]
@ne9z, I have the following issue with the Nix ZFS HOWTO:

NixOS version: 21.11 (stable)

If you aren't using immutable root (i.e. skip [step 12](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS/2-system-configuration.html)), then installation fails:

```
updating GRUB 2 menu...
mount: /boot/efis/ata-XXXXXXXXXX-part1: /dev/sdd1 already mounted on /boot/efis/ata-XXXXXXXXXX-part1.
mount: /boot/efis/ata-XXXXXXXXXX-part1: /dev/sdf1 already mounted on /boot/efis/ata-XXXXXXXXXX-part1.
[...]
installing the GRUB 2 boot loader on /dev/disk/by-id/ata-XXXXXXXXXX...
Installing for i386-pc platform.
Installation finished. No error reported.
[...]
installing the GRUB 2 EFI boot loader into /boot...
Installing for x86_64-efi platform.
/nix/store/[...]-grub-2.06/sbin/grub-install: error: /boot doesn't look like an EFI partition.
/nix/store/[...]-install-grub.pl: installation of GRUB EFI into /boot failed: No such file or directory
```

Step 12 of System Configuration currently reads:

> 12. For immutable root file system, save machine-id and other files:
> ```
> mkdir -p /mnt/state/etc/{ssh,zfs}
> systemd-machine-id-setup --print > /mnt/state/etc/machine-id
> tee -a /mnt/etc/nixos/${INST_CONFIG_FILE} <<EOF
>   systemd.services.zfs-mount.enable = false;
>   environment.etc."machine-id".source = "/state/etc/machine-id";
>   environment.etc."zfs/zpool.cache".source
>     = "/state/etc/zfs/zpool.cache";
>   boot.loader.efi.efiSysMountPoint = "/boot/efis/${INST_PRIMARY_DISK##*/}-part1";
> EOF
> ```

Notice `boot.loader.efi.efiSysMountPoint` is set in the above snippet. Not setting it doesn't work well with the set-up of mounting every ESP into `/boot/efis` and mirroring it in the extra install commands. 

Walking up the stack a bit, `grub-install` (from grub2) is called from `install-grub.pl` (within nixpkgs) with these arguments

```
/nix/store/[snip]-grub-2.06/sbin/grub-install --recheck --target=x86_64-efi --boot-directory=/boot --efi-directory=/boot --no-nvram --removable
```

https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/nixos/modules/system/boot/loader/grub/install-grub.pl#L744

I think it's coming from [`boot.loader.efi.efiSysMountPoint`'s default of `"/boot"`](https://search.nixos.org/options?channel=21.11&show=boot.loader.efi.efiSysMountPoint&from=0&size=50&sort=relevance&type=packages&query=efiSysMountPoint) since we do set `boot.loader.grub.devices` in step 13:

> 13. Configure GRUB boot loader for both legacy boot and UEFI:
> ```
> [...]
>     grub.devices = [
>EOF
>for i in $DISK; do
>  printf "      \"$i\"\n" >>/mnt/etc/nixos/${INST_CONFIG_FILE}
>done
>tee -a /mnt/etc/nixos/${INST_CONFIG_FILE} <<EOF
>    ];
> ```

https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/nixos/modules/system/boot/loader/grub/grub.nix#L721-L723

https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/nixos/modules/system/boot/loader/grub/grub.nix#L40

Setting a value for `boot.loader.efi.efiSysMountPoint` solves the issue and allows `nixos-install` to successfully complete. 

For what it's worth, is there any opinions on simply using `mirroredBoots` which seems intended for this purpose?

**Comment by ne9z** [comment]
> `--efi-directory=/boot`

This is definitely wrong.  It must be one of the paths inside `/boot/efis/disk-part1`

I will investigate this issue later, but please check if primary disk variable was set.

> `mirroredBoots`

I run a 4 disk server.  Previously I used this option to mirror bootloader.  It's great except for one thing:  horribly, terribly slow.  `nixos-rebuild switch` runs like snail with mirroredBoots on.

The issue is, mirroredBoots does not simply copy bootloader to target disks: it regenerates a bootloader for every disk.  Which is **slow** and unnecessary.  I got fed up and replaced it with the current copy scheme.

**Comment by ne9z** [comment]
Apologies for not reading the original issue description well.  The issue is that Step 12 was skiped.

You must do every step **not** explicitly marked as optional.  That is, with the sole exception of Optional Configuration page and the last section of Bootloader page, every other instruction must be followed in order to successfully install the system.  The system is not expected to work if Step 12, or other non-optional step was omitted.

Maybe I should restate this more explicitly in the guide.  What do you think?

**Comment by ne9z** [comment]
If you skip Step 12, there are other troubles waiting for you down the road.

For example, when `zpool.cache` is not set to read-only & empty, boot failure is expected due to stale cache.  Step 12 also includes an option of disabling zfs-mount.  Without this option, there will be mount-disorder on reboot.

**Comment by jacobgreenleaf** [comment]
Yeah I can close this then. I got the impression that it was intended to be optional, but with this issue closed as documentation it should be good enough. Thanks!
