### ISSUE TITLE
NixOS: Allow for a simple config or advanced flake config

### ISSUE THREAD

**Issue by mariaa144** [openzfs/openzfs-docs#417]
Perhaps it makes sense to allow for a barebones simple config for getting started and also recommend an advanced flake repo for those who want a more opinionated setup for how to do many features. I imagine recommending starting with an template flake repo and then use their own repo to track changes manage their hosts with it.

At least the flake repo is how I plan to manage my hosts and I imagine it is how others with several hosts do as well. The guide could point people in the right direction for those cases.

#411

**Comment by ne9z** [comment]
> Perhaps it makes sense to allow for a barebones simple config for
> getting started

There will not be a simple config, because the template flake is already
simple enough.

The current template flake repo **only** contains and only contain what
is needed for ZFS.  Not even desktop environment is enabled.  It is
**not** advanced and I will keep it that way.  It can be used as
traditional configuration.nix.

I will not repeat myself here and I think you have already read my
arguments against the previous approach elsewhere, which was to parse
and edit the output of nixos-generate-config.  It was a nightmare to
maintain and I personally will **not** do that.

> and also recommend an advanced flake repo for those
> who want a more opinionated setup for how to do many features.

No advanced configuration will be documented here or be considered for
inclusion in the template flake repo.

> I imagine recommending starting with an template flake repo and then
> use their own repo to track changes manage their hosts with it.

The repo used right now is already a template and I have already
recommended in the guide to track changes with git.

> At least the flake repo is how I plan to manage my hosts and I imagine
> it is how others with several hosts do as well. The guide could point
> people in the right direction for those cases.

The template flake repo used in the guide already supports per-host
configuration.

Irrelevant to the guide, I am using this same repo to for managing my
several laptops and a home server. You can view the complete
configuration inside the "personal" branch of my repo.

**Comment by mariaa144** [comment]
Great! Thanks for the explanation.
