### ISSUE TITLE
Ubuntu: Build dependencies missing libpam0g-dev and dh-dkms

### ISSUE THREAD

**Issue by jaredjones** [openzfs/openzfs-docs#457]
As of `zfs-2.2`, the Ubuntu required dependencies are missing `libpam0g-dev` and `dh-dksm` which results in the following error when building the project. The OpenZFS documentation should be updated to include this dependency.
```
Unmet build dependencies: libpam0g-dev
```

Note: `dh-dkms` is required as of Ubuntu Mantic to run: `make native-deb-utils` as its no longer part of `dkms` proper.

**Comment by rnickle** [comment]
I can confirm that those packages are required for Debian 12 and Ubuntu 24.04.

Also, I observed for Ubuntu 24.04 the following packages were required, I suspect that they may have been pulled in as dependencies by other packages for Debian 12 because attempting to install them found they were already present:

- libblkid-dev
- dh-autoreconf
- libtirpc-dev

Here is what I tested for Debian 12 and Ubuntu 24.04 for _make native-deb_ and _make native-deb-utils_:

```shell
$ sudo apt install alien autoconf automake build-essential debhelper-compat dh-autoreconf dh-dkms dh-python dkms fakeroot gawk git libaio-dev libattr1-dev libblkid-dev libcurl4-openssl-dev libelf-dev libffi-dev libpam0g-dev libssl-dev libtirpc-dev libtool libudev-dev linux-headers-generic parallel po-debconf python3 python3-all-dev python3-cffi python3-dev python3-packaging python3-setuptools python3-sphinx uuid-dev zlib1g-dev
```
