### ISSUE TITLE
Custom Packages instructions for Debian/Ubuntu will never work

### ISSUE THREAD

**Issue by rincebrain** [openzfs/openzfs-docs#497]
As of this writing:
```
To build RPM converted Debian packages:

$ cd zfs
$ ./configure --enable-systemd
$ make -j1 deb-utils deb-kmod
$ sudo apt-get install --fix-missing ./*.deb

Starting from openzfs-2.2 release, native Debian packages can be built as follows:

$ cd zfs
$ ./configure
$ make native-deb-utils native-deb-kmod
$ rm ../openzfs-zfs-dkms_*.deb
$ sudo apt-get install --fix-missing ../*.deb
```

However, this is going to emit both the `dracut` and `initramfs` helper packages, and in at least Ubuntu, both of those Provide a common thing and Conflict with each other, so if it attempts to install both to satisfy that, it'll fail, as demonstrated in openzfs/zfs#15948.

I've personally used something like:
`sudo apt install $(ls *VERSION*deb | grep -v dracut | while read LINE;do echo -n "./${LINE} ";done;)`

since 2018 for this, looking at my shell history. 

It's probably easiest to just advise people not to install the dracut packages by default, though, with a note explaining how to do the opposite if they're using a not-default initrd generator.

(Opening a bug because I'm busy and don't have time to go through the insane clone-edit-PR loop we turned simply editing a wiki into.)

**Comment by gmelikov** [comment]
Thank you for suggestion! 

Offtopic - we've had github wiki for docs, and the major downside was that only project members could change it. Another downside of wiki-like way is that we can't easily generate pages and add any checks on content. But - you can click "Edit on GitHub" link on interested page, and use Github's UI to easily clone and prepare lightweight PR, of course if you're ready. Otherwise - thank you for issues, I'll work on them gradually.

**Comment by rincebrain** [comment]
Yeah, I get that, but it might be useful to just focus on using the OpenZFS wiki more for some things, rather than on Github.

We could also change the packaging to make it easier to not generate both packages unless we want to, but the PR workflow feels pretty cumbersome at times for editing a wiki, to say nothing of excluding everyone who refuses to use Github.
