### ISSUE TITLE
bpool/BOOT/ubuntu_UUID not mounted

### ISSUE THREAD

**Issue by barnabasJ** [openzfs/openzfs-docs#73]
@rlaager, I have the following issue with the Ubuntu 20.04 Root on ZFS HOWTO:

First of all, thank you for the great HOWTO. I ran into the following issue and I'm not sure what I did wrong. After rebooting only the `bpool/BOOT/ubuntu_UUID/grub` dataset is mounted but not the underlying `bpool/BOOT/ubuntu_UUID`. The `canmount` option on the `bpool/BOOT/ubuntu_UUID` dataset is set to `noauto` and I can't figure out if I missed something where this should get mounted or if there is another problem.

I'd be grateful for any help

**Comment by rlaager** [comment]
Disclaimer: I haven't given this a ton of thought, but I figured some answer was better than no answer.

If I understand the problem correctly, you're saying that `/boot` is not getting mounted. What happens if you try to mount it manually? `/boot/grub` will be in the way, so you need something like:
```
zfs umount bpool/BOOT/ubuntu_UUID/grub
zfs mount bpool/BOOT/ubuntu_UUID
zfs mount bpool/BOOT/ubuntu_UUID/grub
```

If that works, then the next thing I'd check would be the mount cache at `/etc/zfs/zfs-list.cache/bpool`. Make sure that the properties for the `bpool` datasets are properly cached there. If so, check that `/run/systemd/generator/boot.mount` was generated and has sane contents. Finally, see what happened with that unit with e.g. `systemctl status boot.mount` and/or `journalctl -eu boot.mount`.

Let me know what you find. If it's not immediately clear, hopefully this will get us on the right track.

**Comment by barnabasJ** [comment]
I checked everything you wrote and I was able to umount and manually mount everything again. The `/etc/zfs/zfs-list.cache/bpool` file was in place with the following content:

```
bpool   /boot   off     on      on      off     on      off     on      off     -       none
bpool/BOOT      none    off     on      on      off     on      off     on      off     -       none
bpool/BOOT/ubuntu_UUID        /boot   noauto  on      on      off     on      off     on      off     -       none
bpool/BOOT/ubuntu_UUID/grub   /boot/grub      on      on      on      off     on      off     on      off     -       none
```

I then checked for `/run/systemd/generator/boot.mount` which was missing. Afterward, I checked `systemctl status boot.mount` which was running fine and lastly, I checked  `journalctl -eu boot.mount` which was empty. 

I then rebooted the system and `/boot` was not mounted again. 

After the reboot I unmounted and mounted everything again, then ran `zfs set canmount=on bpool/BOOT/ubuntu_UUID`.

The content of the `/etc/zfs/zfs-list.cache/bpool` file changed to: 

```
bpool   /boot   off     on      on      off     on      off     on      off     -       none
bpool/BOOT      none    off     on      on      off     on      off     on      off     -       none
bpool/BOOT/ubuntu_UUID        /boot   on      on      on      off     on      off     on      off     -       none
bpool/BOOT/ubuntu_UUID/grub   /boot/grub      on      on      on      off     on      off     on      off     -       none
```
After rebooting `/boot` was now mounted and the `/run/systemd/generator/boot.mount` existed.


In the HOWTO at step 3.2 it says to create the `bpool/BOOT/ubuntu_UUID` dataset like this:

```
zfs create -o canmount=noauto -o mountpoint=/boot \
    bpool/BOOT/ubuntu_$UUID
```

Later on, in section 5.8 it says to run the following commands to force an update if either of the cache files is empty:

```
zfs set canmount=noauto bpool/BOOT/ubuntu_$UUID
zfs set canmount=noauto rpool/ROOT/ubuntu_$UUID
```

Is setting the `canmount` property to on like I did an ok fix or did I miss something in the HOWTO?

Thank you for your help

**Comment by rlaager** [comment]
I have an idea, but I'm not positive. The HOWTO definitely has us creating that datasets (so clearly it should serve some purpose / past me thought so). I have a test VM that I think was created using the Ubuntu installer and it has one (so that's a good reason to have it). However, you're clearly correct that the HOWTO says to set `canmount=noauto`.

What I think is happening here is that zsys was overridding that `canmount=noauto`. This was the source of another, serious bug, which has since been fixed. But I've been swamped and haven't had a chance to retest everything and incorporate that new fix. (It's non-trivial, as I have to revert the `/boot/grub` errata!) My hunch, as of right now, is that fixing that bug has lead to the `/boot` dataset _not_ getting `canmount=noauto` overridden, so then it does not mount for you.

In the immediate term, I think it's fine to leave that as `canmount=on`. Are the contents of `/boot` in that filesystem? Probably, if you just installed it? If not (and only if not), then here's my suggestion on how to fix that (i.e. move the contents of /boot from the root filesystem to the separate /boot filesystem):
1. Unmount `/boot/grub` and `/boot`.
2. Move it out of the way: `mv /boot /boot2`
3. Recreate (`mkdir /boot`) and remount `/boot`
4. Copy the contents from the root filesystem into the /boot filesystem: `cp -a /boot2/* /boot`
5. Remount `/boot/grub`
6. Update GRUB for good measure: `update-grub`
7. Reboot the system
8. Assuming the system boots correctly, you can then delete /boot2: `rm -rf /boot2`

In the unlikely event that the system fails to boot, you'll have to boot off a Live CD, import the pool, mount the root filesystem, and move the contents of /boot2 into /boot (on the root filesystem, i.e. without /boot mounted). I'm pretty confident this won't happen, but maybe GRUB has some reference to /boot that I'm not aware of.

I'll try to get to reviewing this soon. Basically, I need to re-test everything with current Ubuntu 20.04 and then update the instructions for the new/old /boot/grub layout and probably change `bpool/BOOT/ubuntu_UUID` to be `canmount=on`.

**Comment by barnabasJ** [comment]
Thanks again for your help, everything works as expected now. Now that I read your answer I'm pretty sure what happend. 
I didn't install zsys this time because I had problems with my first 20.04 install using zsys and decided I wanted to manage snapshots myself. 

Do you think this could lead to problems in the future?

**Comment by rlaager** [comment]
I removed the unnecessary `canmount=noauto` here. However, the HOWTO is assuming zsys. I can't speak for how things will behave without zsys installed. I think the biggest risk would be if you are managing boot environment clones yourself. In that case, you likely want `canmount=noauto` on things under rpool/ROOT/ and maybe bpool/BOOT (depending on what you are doing there) to avoid two things trying to mount at once. But I'm not at all sure of that at the moment, as I did not research or test it.
