### ISSUE TITLE
Ubuntu 20.04 ZFS Root: boot pool naming -not- arbitrary

### ISSUE THREAD

**Issue by bobziuchkovski** [openzfs/openzfs-docs#85]
Currently 20.04 ZFS Root docs state:

```
   - The pool name is arbitrary. If changed, the new name must be used
     consistently. The bpool convention originated in this HOWTO.
```

It turns out the `bpool` name is actually required.  The `/etc/grub.d/10_linux_zfs` scripts installed by grub-common contain a couple hard-coded references to `bpool` that are used when scanning for boot entries.

I found this the hard way by using `<hostname>-bpool` for my boot pool and having grub fail to boot.  Thankfully I remembered just enough grub-fu to insert the correct modules, pass manual boot args, and then debug the issue.

It seems like there are at least several potential fixes:

  * Work with the Ubuntu grub maintainers to update that script to support arbitrary boot pool names
  * Document some sort of workaround patch in the docs (such as a sed replacement of `bpool` in /etc/grub.d/10_linux_zfs)
  * Update the docs to state that the `bpool` naming convention is actually necessary.

I'd personally prefer the first option, but I think that might also involve updating the guide to run the `apt dist-upgrade` step prior to the initial grub install.  Otherwise debootstrap wouldn't pull in the updated grub-common (I think?).

In any event, I'm happy to help post a PR with doc updates, but would be interested in getting thoughts/feedback on the described situation first.  Thanks!

**Comment by rlaager** [comment]
Good catch! Thanks! I hadn't tested renaming the bpool (at least not with 20.04). (I still haven't tested it, but I'll take your word for it, and I do see the `bpool` in `/etc/grub.d/10_linux_zfs`.

I modified the text to address this. If you have better text, please feel free to submit a PR.

Since the file is in `/etc`, it is a conffile, so editing it is a supported thing (at least to some extent). If (on upgrade) the GRUB package changes its contents, you'll get a `dpkg` conflict message and you'll have to sort it out.

**Comment by bobziuchkovski** [comment]
Good point on the /etc conflict handling.  That's probably good enough for me.  Thanks!
