### ISSUE TITLE
Fresh Debian 10.7 "converting" to root zpool issues encountered

### ISSUE THREAD

**Issue by hevisko** [openzfs/openzfs-docs#97]
While "converting" Debian 10.7 fresh installations to zpool (2nd disk to be mirrored later), @rlaager, I have the following issue with the Debian Buster Root on ZFS HOWTO:

My process:
0) Done a "clean" Debian installation (as I would expect from a hosting provider's Dedicated servers)
00) instead of debootstrap, I "just" do a `rsync -vaPx / /mnt` (repeating for /boot etc. as need be)

1) Seems that `/run` needs to be `mount --rbind` (or at least a tmpfs) before the chroot, else the `zed` step fails without the /var/lock -> /run/lock not valid.

2) secondary zpools aren't mounted 'cause of bpool service, see https://github.com/openzfs/zfs/discussions/8549#discussioncomment-231334
for the advice to add lines to preserve the zpool.cache in the bpool service file.

**Comment by rlaager** [comment]
For item 1, I'm hesitant to suggest bind mounting `/run` from the Live CD into the chroot. I worry that something might conflict. So I think the alternate approach of mounting a tmpfs there seems safer. I've implemented this. (I haven't actually tested, but it seems safe enough.)

For item 2, that comment recommends a work-around involving moving the cache file and then restoring it. The workaround is suppressing errors with `|| true`, which can be done by prefixing the command with `-`. And if we are suppressing errors anyway, I'm not sure there's a benefit to checking for the file rather than just trying the move and letting it fail. This avoids the shell. Are you able to test and confirm if this works just as well?
```
ExecStartPre=-/bin/mv /etc/zfs/zpool.cache /etc/zfs/preboot_zpool.cache
ExecStart=/sbin/zpool import -N -o cachefile=none bpool
ExecStartPost=-/bin/mv /etc/zfs/preboot_zpool.cache /etc/zfs/zpool.cache
```

**Comment by hevisko** [comment]
yeah, systemd ;(

For item 2: yes, the preliminary tests seems to work on my test bed.

**Comment by rlaager** [comment]
Thanks for testing! I've updated the docs accordingly.
